clone_folder: C:\Vortex2D
platform:
  - x64
build_script:
  - mkdir build && cd build
  - cmake -G"Visual Studio 14 Win64" .. -DVORTEX2D_ENABLE_TESTS=ON -DVORTEX2D_ENABLE_EXAMPLES=ON
  - cmake --build .
