platform: linux/arm

pipeline:
  build:
    image: vulkan
    privileged: true
    commands:
      - mkdir build && cd build
      - cmake .. -DVORTEX2D_ENABLE_TESTS=On -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_FLAGS="-Wno-psabi"
      - make -j4
      - cd Tests && ./vortex2d_tests
      # Uploading report to Coveralls
      - bash <(curl -s https://codecov.io/bash)