platform: linux/arm

pipeline:
  build:
    image: vulkan
    commands:
      - mkdir build && cd build
      - cmake .. -DVORTEX2D_ENABLE_TESTS=On -DCMAKE_BUILD_TYPE=Coverage -DCMAKE_CXX_FLAGS="-Wno-psabi"
      - make -j4
  test:
    image: vulkan
    privileged: true
    when:
      status: [ success ]
    commands:
      - ./build/Tests/vortex2d_tests
  coverage:
    image: vulkan
    when:
      status: [ success ]
    commands:
      - ./Scripts/codecov.sh
