sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

before_install:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - sudo apt-get update -qq
  - sudo apt-get install -y mesa-utils libosmesa6 xvfb build-essential libxmu-dev libxi-dev libglapi-mesa-lts-xenial libgl1-mesa-glx-lts-xenial libgl1-mesa-dev-lts-xenial 
# Vortex2D dependencies
  - sudo apt-get install -y libgtest-dev
# GLFW3 dependencies
  - sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

install:
# GLFW 3.1.1 install
  - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
  - unzip glfw-3.2.1.zip
  - cd glfw-3.2.1
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install
  - cd ..
#GLEW 2.0.0 install
  - git clone https://github.com/nigels-com/glew.git
  - git checkout tags/glew-2.0.0
  - cd glew/auto
  - make
  - cd ..
  - make
  - sudo make install
  - cd ..
#GLM install
  - git clone https://github.com/g-truc/glm.git
  - git checkout tags/0.9.8.4
  - cd glm
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
#Gtest install
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd -

before_script:
  - mkdir build
  - cd build
  - cmake .. && make
script:
  - ctest
