sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      # Vortex2D dependencies
      - google-mock
      # GLFW3 dependencies
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      # Mesa dependencies
      - xserver-xorg-video-dummy
      - xpra
      - mesa-utils

before_install:
  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers
  - sudo apt-get update -qq -y
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -yq --force-yes install libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker2 xvfb

install:
# GLFW 3.1.1 install
  - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
  - unzip glfw-3.2.1.zip
  - cd glfw-3.2.1
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install
  - cd ..
#GLEW 2.0.0 install
  - git clone https://github.com/nigels-com/glew.git
  - cd glew
  - git checkout tags/glew-2.0.0
  - cd auto
  - make
  - cd ..
  - make
  - sudo make install
  - cd ..
  - sudo ln -s /usr/lib64/libGLEW.so.2.0 /usr/lib/libGLEW.so.2.0
#GLM install
  - git clone https://github.com/g-truc/glm.git
  - cd glm
  - git checkout tags/0.9.8.4
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
#Gtest&Gmock install
  - cd /usr/src/gmock/gtest
  - sudo cmake -Dgtest_disable_pthreads=ON .
  - sudo make
  - sudo mv libg* /usr/lib/
  - sudo cp -r include/gtest /usr/include/gtest/
  - cd ..
  - sudo cmake -Dgtest_disable_pthreads=ON .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - xpra --xvfb="Xorg +extension GLX +extension RANDR +extension RENDER -config Tests/Config/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :99
  - sleep 3
  - cat ${HOME}/.xpra/xorg.log
  - glxinfo

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
