branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9.4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # Modern GCC
      - gcc-5
      - g++-5
      # Vortex2D dependencies
      - cmake
      - doxygen
      # GLFW3 dependencies
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev

cache: ccache

install:
# Doxyrest
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user sphinx sphinx_rtd_theme breathe; fi
# LunarG SDK install
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://vulkan.lunarg.com/sdk/download/1.1.77.0/linux/vulkansdk-linux-x86_64-1.1.77.0.tar.gz; tar xf vulkansdk-linux-x86_64-1.1.77.0.tar.gz; . 1.1.77.0/setup-env.sh; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://vulkan.lunarg.com/sdk/download/1.1.77.0/mac/vulkansdk-macos-1.1.77.0.tar.gz; tar xf vulkansdk-macos-1.1.77.0.tar.gz; fi

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. -DVORTEX2D_ENABLE_TESTS=On -DVORTEX2D_ENABLE_EXAMPLES=On -DVORTEX2D_ENABLE_DOCS=On -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -DMOLTENVK_DIR=../vulkansdk-macos-1.1.77.0/MoltenVK -DGLSL_VALIDATOR=../vulkansdk-macos-1.1.77.0/macOS/bin/glslangValidator -DVORTEX2D_ENABLE_TESTS=On -DVORTEX2D_ENABLE_EXAMPLES=On -DCMAKE_BUILD_TYPE=Debug; fi
  - make -j 4