sudo: required
dist: trusty
language: cpp

compiler:
  - clang

before_install:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - sudo apt-get update -qq
  - sudo apt-get install -y libglm-dev libgtest-dev mesa-utils libosmesa6 xvfb build-essential libxmu-dev libxi-dev libglapi-mesa-lts-xenial libgl1-mesa-glx-lts-xenial libgl1-mesa-dev-lts-xenial libxrandr-dev libxinerama-dev libxcursor-dev
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
# GLFW 3.1.1 install
  - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
  - unzip glfw-3.2.1.zip
  - cd glfw-3.2.1
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install
  - cd ..
#GLEW 2.0.0 install
  - git clone https://github.com/nigels-com/glew.git
  - cd glew
  - make GLEW_DEST=/usr
  - sudo make install GLEW_DEST=/usr
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest
