sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

branches:
  only:
    - master

# Travis CI is powered with Ubuntu 12.04, whose toolchain is outdated.
addons:
  apt:
    # Travis white list of ppa.
    # https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    sources:
      - ubuntu-toolchain-r-test     # For gcc 4.9
    packages:
      - g++-4.9
      # Vortex2D dependencies
      - libgtest-dev
      # GLFW3 dependencies
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      # For headless rendering
      # - libxi-dev
      # - libxmu-dev
      # - libxv-dev
      - xserver-xorg-video-dummy
      - xpra
      - xorg-dev
      - libgl1-mesa-dev
      - mesa-utils
      - libgl1-mesa-glx

before_install:
# Modern GCC/Clang versions
  - if [ "$CC" = "gcc"   ]; then export CC=gcc-4.9 CXX=g++-4.9; fi       # Make sure that gcc-4.9 is selected.
  - if [ "$CC" = "clang" ]; then export CC=clang-3.6 CXX=clang++-3.6; fi # Make sure that clang-3.6 is selected.
# Dependencies for headless rendering
  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers",
  - sudo apt-get update -qq -y
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-common-dev libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker-dev xvfb

install:
# GLFW 3.1.1 install
  - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
  - unzip glfw-3.2.1.zip
  - cd glfw-3.2.1
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install
  - cd ..
#GLEW 2.0.0 install
  - git clone https://github.com/nigels-com/glew.git
  - cd glew
  - git checkout tags/glew-2.0.0
  - cd auto
  - make
  - cd ..
  - make
  - sudo make install
  - cd ..
  - sudo ln -s /usr/lib64/libGLEW.so.2.0 /usr/lib/libGLEW.so.2.0
#GLM install
  - git clone https://github.com/g-truc/glm.git
  - cd glm
  - git checkout tags/0.9.8.4
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
#Gtest install
  - cd /usr/src/gtest
  - sudo cmake -Dgtest_disable_pthreads=ON .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd -

before_script:
# For headless rendering
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - xpra --xvfb=\"Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log\"  start :99
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
  - sleep 3

script:
  - mkdir build
  - cd build
  - cmake .. 
  - make -j 4
  - cd Tests
  - ctest --verbose
