sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

branches:
  only:
    - master

addons:
  apt:
    packages:
      # Vortex2D dependencies
      - libgtest-dev
      - google-mock
      # GLFW3 dependencies
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev

install:
# GLFW 3.1.1 install
  - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
  - unzip glfw-3.2.1.zip
  - cd glfw-3.2.1
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install
  - cd ..
#GLEW 2.0.0 install
  - git clone https://github.com/nigels-com/glew.git
  - cd glew
  - git checkout tags/glew-2.0.0
  - cd auto
  - make
  - cd ..
  - make
  - sudo make install
  - cd ..
  - sudo ln -s /usr/lib64/libGLEW.so.2.0 /usr/lib/libGLEW.so.2.0
#GLM install
  - git clone https://github.com/g-truc/glm.git
  - cd glm
  - git checkout tags/0.9.8.4
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
#Gtest install
  - cd /usr/src/gtest
  - sudo cmake -Dgtest_disable_pthreads=ON .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd -

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4
