sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: Vortex2D
    - DOXYFILE: Doxyfile
    - GH_REPO_REF: github.com/mmaldacker/Vortex2D.git
    - secure: "XdKG1w18LP9346CJclS4FbRTYFZImPexTHQgzQcFGimBY0teubeMUKDs2Ah+f962ndxUFOZapXgAwPW0eVV8Zq8VIS80mthjuFqOREp5AuDGHoPjz/tSNBHkcQFddSa1T7Wt4r2WvKooriuM6sj3mIm1kMHxifrGUJI4z9xLd11BESo9i3BnENqv31T9Q2sdKQJRz2pLzVgoTHOq65G4DFQZ7MYKZncaepWacJSLlKQrYIKHqsJSLL3FVQ1SBvcc93nlDwIxfrv+U7tSfRXtHD5OqVLGWMASUSr7IE//wvd+w5WCedraFoc5N7qDbgH9glGzVxl7b5UxmP74A+lfacz+ENnItdUqm7YUEhzgNbp2/th3BbcVoBk1oSaatqXR02r500kkaLFget7oU0WYt36wNX3/RyXYAUnivWNbRA4Ch9N50stkkU1q0QbshAcfCZgPPVhTZ3DVsdihxRf+wYpQCe6EOAzsF0La8XJ6hsj1BpbPUguZCeTOM/cHI9gc36wSzPhkT4QuPr0/yI2F58vtVvBOBowwm38gC9BPe/e7wALQXWj4XWFVt7uUbiuuO8mpKgTlOZNf1vLmKw9jxq84G7X4GuxgrgVavZ5UGR9IZU8H3BN+6IOEpRfan7s/JpHyeKADXUonnUobkll16JUpde6g6VJAnD2EGyqKgh0="

addons:
  apt:
    packages:
      # Vortex2D dependencies
      - google-mock
      - doxygen
      # GLFW3 dependencies
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      # Mesa dependencies
      - mesa-utils
      - python-mako

install:
# Mesa 13.0.4 install
  - wget ftp://ftp.freedesktop.org/pub/mesa/13.0.4/mesa-13.0.4.tar.gz
  - tar xvzf mesa-13.0.4.tar.gz
  - cd mesa-13.0.4
  - ./configure --enable-opengl --disable-gles1 --disable-gles2 --disable-va --disable-xvmc --disable-vdpau --with-gallium-drivers=swrast --disable-dri --with-dri-drivers= --disable-egl --with-egl-platforms= --disable-gbm --disable-glx --disable-osmesa --enable-gallium-osmesa --enable-texture-float --with-llvm-prefix=/usr
  - make -j 4
  - sudo make install
  - cd ..
# GLFW masterinstall
  - wget -O glfw-master.zip https://github.com/glfw/glfw/archive/master.zip
  - unzip glfw-master.zip
  - cd glfw-master
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu -DGLFW_USE_OSMESA=ON
  - make
  - sudo make install
  - cd ..
#GLEW master install
  - git clone https://github.com/nigels-com/glew.git
  - cd glew
  - make -C auto
  - pushd build/cmake; cmake -G 'Unix Makefiles' -DGLEW_OSMESA=1 . ; make; sudo make install; popd
  - cd ..
#GLM install
  - git clone https://github.com/g-truc/glm.git
  - cd glm
  - git checkout tags/0.9.8.4
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
#Gtest&Gmock install
  - cd /usr/src/gmock/gtest
  - sudo cmake -Dgtest_disable_pthreads=ON .
  - sudo make
  - sudo mv libg* /usr/lib/
  - sudo cp -r include/gtest /usr/include/gtest/
  - cd ..
  - sudo cmake -Dgtest_disable_pthreads=ON .
  - sudo make
  - sudo mv libg* /usr/lib/
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - glxinfo

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 4

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/Docs
  - chmod +x generatePublishDocs.sh
  - ./generatePublishDocs.sh
