sudo: required
dist: trusty
language: cpp

compiler:
 - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libglm-dev libglfw3-dev libglew-dev libgtest-dev

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ctest
