sudo: required
dist: trusty
language: cpp

branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: Vortex2D
    - DOXYFILE: Doxyfile
    - GH_REPO_REF: github.com/mmaldacker/Vortex2D.git
    - secure: "XdKG1w18LP9346CJclS4FbRTYFZImPexTHQgzQcFGimBY0teubeMUKDs2Ah+f962ndxUFOZapXgAwPW0eVV8Zq8VIS80mthjuFqOREp5AuDGHoPjz/tSNBHkcQFddSa1T7Wt4r2WvKooriuM6sj3mIm1kMHxifrGUJI4z9xLd11BESo9i3BnENqv31T9Q2sdKQJRz2pLzVgoTHOq65G4DFQZ7MYKZncaepWacJSLlKQrYIKHqsJSLL3FVQ1SBvcc93nlDwIxfrv+U7tSfRXtHD5OqVLGWMASUSr7IE//wvd+w5WCedraFoc5N7qDbgH9glGzVxl7b5UxmP74A+lfacz+ENnItdUqm7YUEhzgNbp2/th3BbcVoBk1oSaatqXR02r500kkaLFget7oU0WYt36wNX3/RyXYAUnivWNbRA4Ch9N50stkkU1q0QbshAcfCZgPPVhTZ3DVsdihxRf+wYpQCe6EOAzsF0La8XJ6hsj1BpbPUguZCeTOM/cHI9gc36wSzPhkT4QuPr0/yI2F58vtVvBOBowwm38gC9BPe/e7wALQXWj4XWFVt7uUbiuuO8mpKgTlOZNf1vLmKw9jxq84G7X4GuxgrgVavZ5UGR9IZU8H3BN+6IOEpRfan7s/JpHyeKADXUonnUobkll16JUpde6g6VJAnD2EGyqKgh0="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # Modern GCC
      - gcc-5
      - g++-5
      # Vortex2D dependencies
      - cmake
      - doxygen
      - liblua5.3-dev
      - libexpat1-dev
      # GLFW3 dependencies
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev

install:
# Doxyrest
 - pip install --user sphinx sphinx_rtd_theme
 - wget https://github.com/vovkos/doxyrest/releases/download/doxyrest-1.1.0/doxyrest-linux-1.1.0-amd64.tar.xz
 - tar xf doxyrest-linux-1.1.0-amd64.tar.xz
 - export DOXYREST_BIN=${TRAVIS_BUILD_DIR}/doxyrest-linux-1.1.0-amd64/bin
 - export DOXYREST_FRAME=${TRAVIS_BUILD_DIR}/doxyrest-linux-1.1.0-amd64/share/doxyrest/frame
 - export DOXYREST_SPHINX=${TRAVIS_BUILD_DIR}/doxyrest-linux-1.1.0-amd64/share/doxyrest/frame
# LunarG SDK install
 - wget https://vulkan.lunarg.com/sdk/download/1.0.65.0/linux/vulkansdk-linux-x86_64-1.0.65.0.run
 - chmod +x vulkansdk-linux-x86_64-1.0.65.0.run
 - ./vulkansdk-linux-x86_64-1.0.65.0.run
 - cd VulkanSDK/1.0.65.0/
 - ./build_tools.sh
 - . setup-env.sh
# Lua
 - git clone https://github.com/LuaDist/lua.git --quiet
 - cd lua/
 - git checkout -qf 5.2.4
 - mkdir build && cd build && cmake .. && make -j4 && sudo make install

script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake .. -DVORTEX2D_ENABLE_TESTS=On -DVORTEX2D_ENABLE_EXAMPLES=On -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5
  - make -j 4

# Generate and deploy documentation
after_success:
  # Compile & Upload docs
  - cd $TRAVIS_BUILD_DIR/Docs; chmod +x generatePublishDocs.sh; ./generatePublishDocs.sh